#!/usr/bin/python3
from sys import argv

def factors(q):
    """FACTORS
       Accept number q from file
       Return: n and p
    """
    n = 1
    p = 2
    while q % p != 0:
        p += 1
    n = q / p

    print(f"{q}={int(n)}*{p}")
try:
    with open(argv[1]) as f:
        for number in f:
            factors(eval(number))
except OSError as e:
    print('open() failed', e)
